stinkies/game1/urls.py
from django.urls import path

from game1 import views

app_name = "game1"

urlpatterns = [
    path('', views.homepage_view, name="homepage"),
    path('buy/stinky/new/', views.buy_new_stinky_view, name="buy-new-stinky"),
    path('sell/<int:inventory_item_id>/', views.sell_back_stinky_view, name="sell-back-stinky"),
    path('player/<slug:username>/', views.view_player_view, name="view-player"),
    path('trade/<int:inv_id>/', views.trade_item_view, name="trade-stinky"),
    path('trade/<int:inv_id>/cancel/', views.dont_trade_item_view, name="dont-trade-stinky"),
]

stinkies/stinkies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from portal import views

urlpatterns = [
    path('', views.homepage_view, name="homepage"),
    path('admin/', admin.site.urls),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('friendship/', include('friendship.urls')),
    path('g1/', include('game1.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stinkies/game1/models.py
from django.contrib.auth.models import User
from django.db import models
from django_extensions.db.models import TimeStampedModel


DEFAULT_NEW_PLAYER_COINS = 12
DEFAULT_NEW_ITEM_COST = 2


class Stinky(models.Model):
    name = models.CharField(max_length=255, unique=True)
    price = models.PositiveIntegerField(default=DEFAULT_NEW_ITEM_COST)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "stinky"
        verbose_name_plural = "stinkies"


class InventoryItem(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="inventory")
    item = models.ForeignKey(Stinky, on_delete=models.CASCADE)
    bought_for = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.item)

    def is_for_trade(self):
        return self.item.for_trade.first()


class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    coins = models.PositiveIntegerField(default=DEFAULT_NEW_PLAYER_COINS)

    def __str__(self):
        return "{}".format(self.user)


class WantsToTrade(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="wants_to_trade")
    item = models.ForeignKey(Stinky, on_delete=models.CASCADE, related_name='for_trade')

stinkies/portal/models.py
from django.db import models

# Create your models here.

stinkies/game1/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from friendship.models import Friend

from game1.models import InventoryItem, Player, WantsToTrade
from game1.services import buy_a_stinky, sell_back_stinky


def get_player(request):
    if request.user.is_authenticated:
        player, created = Player.objects.get_or_create(user=request.user)
        return player
    return None


@login_required
def homepage_view(request):
    player = get_player(request)

    context = {
        'player': player,
        'inventory': request.user.inventory.all(),
        'friends': Friend.objects.friends(request.user),
    }
    return render(request, "game1/homepage.html", context=context)


@login_required
def buy_new_stinky_view(request):
    player = get_player(request)
    new_item = buy_a_stinky(player)

    if new_item:
        messages.success(request, "Congratulations! You bought a new stinky: {}".format(new_item.item))
    else:
        messages.error(request, "Sorry! You don't have enough coins for a new stinky.")

    return redirect('game1:homepage')


@login_required
def sell_back_stinky_view(request, inventory_item_id):
    player = get_player(request)
    inventory_item = get_object_or_404(InventoryItem, id=inventory_item_id, user=player.user)
    sell_price = sell_back_stinky(player, inventory_item)
    messages.success(request, "Sold a stinky for {} coin(s).".format(sell_price))
    return redirect('game1:homepage')


@login_required
def view_player_view(request, username):
    player1 = get_player(request)
    player2 = get_object_or_404(Player, user__username=username)
    context = {
        'player': player1,
        'player2': player2,
    }
    return render(request, "game1/player_details.html", context=context)


@login_required
def trade_item_view(request, inv_id):
    inventory_item = get_object_or_404(InventoryItem, id=inv_id, user=request.user)
    other_wtt = WantsToTrade.objects.exclude(user=request.user).order_by('?').first()
    if not other_wtt:
        wtt, created = WantsToTrade.objects.get_or_create(user=request.user, item=inventory_item.item)
        if created:
            messages.info(request, "Stinky is now open for trading: {}".format(wtt.item))
        else:
            messages.warning(request, "Stinky is ALREADY open for trading: {}".format(wtt.item))
    else:
        inventory_item.user = other_wtt.user
        inventory_item.save()
        their_inv = InventoryItem.objects.get(user=other_wtt.user, item=other_wtt.item)
        their_inv.user = request.user
        their_inv.save()
        messages.success(request, "You traded '{}' for '{}'".format(inventory_item.item, their_inv.item))
    return redirect('game1:homepage')


@login_required
def dont_trade_item_view(request, inv_id):
    inventory_item = get_object_or_404(InventoryItem, id=inv_id, user=request.user)
    wtt = WantsToTrade.objects.filter(user=request.user, item=inventory_item.item).first()
    if wtt:
        wtt.delete()
        messages.info(request, "Stinky is no longer open for trading: {}".format(wtt.item))
    else:
        messages.error(request, "This stinky is gone! {}".format(wtt.item))
    return redirect('game1:homepage')

stinkies/portal/views.py
from django.contrib import messages
from django.shortcuts import render
from django.utils.safestring import mark_safe
from friendship.models import Friend


def homepage_view(request):
    context = {
    }
    if request.user.is_authenticated:
        friendship_requests = Friend.objects.requests(request.user)
        for frq in friendship_requests:
            msg = "{0} wants to be friends with you! <a href='#' id='frq_accept' onclick='accept_frq(\"{1}\");'>Accept</a> | <a id='frq_reject' href='#'>Reject</a>".format(frq.from_user, frq.id)
            messages.info(request, mark_safe(msg))
        context['frqs'] = friendship_requests
    return render(request, "portal/homepage.html", context=context)

stinkies/templates/django_registration/registration_complete.html
{% extends "portal/base.html" %}

{% block content %}
<h1>Well done! You are now officially a Stinky Player!</h1>

<div class="text-center">
    <a href="{% url "game1:homepage" %}" class="btn btn-lg btn-info">Play Stinkies</a>
</div>
{% endblock %}

stinkies/templates/django_registration/registration_form.html
{% extends "portal/base.html" %}
{% load bootstrap4 %}

{% block content %}
<h1>New player sign-up</h1>
<form method="post" action="{% url "django_registration_register" %}">{% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button type="submit" class="btn btn-info">Sign up</button>
    <a href="{% url "django_registration_register" %}" class="btn btn-secondary">Existing player</a>
    {% endbuttons %}
</form>
{% endblock %}

stinkies/templates/friendship/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Friendship</title>
</head>
<body>
{% block header %}
    {% include 'header.html' %}
{% endblock header %}
{% block content %}{% endblock content %}
</body>
</html>

stinkies/templates/friendship/block/add.html
{% if not followee_username == request.user.username %}
{% if errors %}<p>{{ errors|join:", " }}</p>{% endif %}
<form method="post">
{% csrf_token %}
<input type="hidden" name="blocked_username" value="{{ blocked_username }}" />
<input type="submit" value="block {{ blocked_username }}" />
</form>
{% endif %}

stinkies/templates/friendship/block/blocked_list.html
{% block content %}
{% load friendshiptags %}
<h1>Blocking</h1>
{% get_by_name friendship_context_object_name as var %}
{% blocking var %}
{% endblock %}

stinkies/templates/friendship/block/blockers_list.html
{% block content %}
{% load friendshiptags %}
<h1>Blocking</h1>
{% get_by_name friendship_context_object_name as var %}
{% blocking var %}
{% endblock %}

stinkies/templates/friendship/block/blocking_list.html
{% block content %}
{% load friendshiptags %}
<h1>Blockers</h1>
{% get_by_name friendship_context_object_name as var %}
{% blockers var %}
{% endblock %}

stinkies/templates/friendship/block/remove.html
<form method="post">
{% csrf_token %}
<input type="hidden" name="blocked_username" value="{{ blocked_username }}" />
<input type="submit" value="remove {{ blocked_username }} from block list" />
</form>

stinkies/templates/friendship/follow/add.html
{% if not followee_username == request.user.username %}
{% if errors %}<p>{{ errors|join:", " }}</p>{% endif %}
<form method="post">
{% csrf_token %}
<input type="hidden" name="followee_username" value="{{ followee_username }}" />
<input type="submit" value="start following {{ followee_username }}" />
</form>
{% endif %}

stinkies/templates/friendship/follow/followers_list.html
{% block content %}
{% load friendshiptags %}
<h1>Followers</h1>
{% get_by_name friendship_context_object_name as var %}
{% followers var %}
{% endblock %}

stinkies/templates/friendship/follow/following_list.html
{% block content %}
{% load friendshiptags %}
<h1>Following</h1>
{% get_by_name friendship_context_object_name as var %}
{% following var %}
{% endblock %}

stinkies/templates/friendship/follow/remove.html
<form method="post">
{% csrf_token %}
<input type="hidden" name="followee_username" value="{{ followee_username }}" />
<input type="submit" value="remove {{ followee_username }} as a friend" />
</form>

stinkies/templates/friendship/friend/add.html
{% if not to_username == request.user.username %}
{% if errors %}<p>{{ errors|join:", " }}</p>{% endif %}
<form method="post">
{% csrf_token %}
<input type="hidden" name="to_username" value="{{ to_username }}" />
<input type="submit" value="add {{ to_username }} as a friend" />
</form>
{% endif %}

stinkies/templates/friendship/friend/request.html
<div>{{ friendship_request.from_user }} wants to be friends with {{ friendship_request.to_user }}</div>

<form method="post" action="{% url 'friendship_accept' friendship_request.pk %}">
{% csrf_token %}
<input type="submit" value="accept" />
</form>

<form method="post" action="{% url 'friendship_reject' friendship_request.pk %}">
{% csrf_token %}
<input type="submit" value="reject" />
</form>

stinkies/templates/friendship/friend/requests_list.html
<ul>
{% for friendship_request in requests %}
    <li>{{ friendship_request.from_user }} to {{ friendship_request.to_user }} <a href="{% url 'friendship_requests_detail' friendship_request.id %}">view</a></li>
{% empty %}
</ul>
<div>no requests :(</div>
{% endfor %}

stinkies/templates/friendship/friend/user_list.html
{% block content %}
{% load friendshiptags %}
<h1>Your Friends</h1>
{% get_by_name friendship_context_object_name as var %}
{% friends var %}
{% endblock %}

stinkies/templates/friendship/header.html
<div id="link_nav">
hello {{ user.username }} <a href="{% url 'friendship_requests' %}">friendship requests</a>
</div>

stinkies/templates/friendship/templatetags/blockers.html
<ul>
    {% for f in blockers %}
    <li>{{ f.first_name }} {{ f.last_name }}</li>
    {% endfor %} 
</ul> 

stinkies/templates/friendship/templatetags/blocking.html
<ul>
    {% for f in blocking %}
    {% if f.first_name or f.last_name %}
    <li>{{ f.first_name }} {{ f.last_name }}</li>
    {% else %}
    <li>{{ f.username }}</li>
    {% endif %}
    {% endfor %}
</ul>

stinkies/templates/friendship/templatetags/followers.html
<ul>
    {% for f in followers %}
    <li>{{ f.first_name }} {{ f.last_name }}</li>
    {% endfor %} 
</ul> 

stinkies/templates/friendship/templatetags/following.html
<ul>
    {% for f in following %}
    {% if f.first_name or f.last_name %}
    <li>{{ f.first_name }} {{ f.last_name }}</li>
    {% else %}
    <li>{{ f.username }}</li>
    {% endif %}
    {% endfor %}
</ul>

stinkies/templates/friendship/templatetags/friend_count.html
{% if friend_count %}{{ friend_count }}{% endif %}

stinkies/templates/friendship/templatetags/friend_rejected_count.html
{% if friend_rejected_count %}{{ friend_rejected_count }}{% endif %}

stinkies/templates/friendship/templatetags/friend_request_count.html
{{ friend_request_count }}

stinkies/templates/friendship/templatetags/friend_requests.html
<ul>
    {% for friend_request in friend_requests %}
        <li>{{ friend_request }}</li>
    {% endfor %}
</ul>

stinkies/templates/friendship/templatetags/friends.html
<ul>
{% for f in friends %}
   {% if f.first_name or f.last_name %}
   <li>{{ f.username }} ({{ f.first_name }} {{ f.last_name }})</li>
   {% else %}
   <li>{{ f.username }}</li>
   {% endif %}
{% endfor %}
</ul>

stinkies/templates/friendship/user_actions.html
{% extends "game1/layout.html" %}

{% block content %}
<div class="row">
    <div class="col">
        <ul>
        {% for list_user in users %}
            {% if user and list_user != user %}
            <li>
                {{ list_user.username }} ({{ list_user.inventory.count }} stinkies) | <a href="#" onclick="add_friend('{{ list_user.username }}');">add as friend</a> | <a href="{% url 'follower_add' list_user.username %}">follow user</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if users.count < 2 %}
            <p>There are no more player you can add.</p>
        {% endif %}
        </ul>
        <div class="text-center">
            <a href="#" class="btn btn-secondary disabled">Invite a friend</a>
        </div>
    </div>
    <div class="col">
        <form id="controlForm" method="post" action="">{% csrf_token %}
            <input type="submit" value="add friend" />
        </form>
    </div>
</div>
{% endblock %}

{% block extra_js %}
function add_friend(username) {
    base_url = "{% url 'friendship_add_friend' 'XXXX' %}";
    post_url = base_url.replace('XXXX', username);
    frm = $('#controlForm');
    frm.attr('action', post_url);
    frm.submit();
};
{% endblock %}

stinkies/templates/game1/homepage.html
{% extends "game1/layout.html" %}

{% block content %}
<h1>{{ request.user }}'s Stinkies</h1>
<h2>Your coins: {{ player.coins|default:0 }}</h2>
<h2>Your inventory:</h2>
<div class="row mb-3">
    <div class="col-8">
    {% for stinky in inventory %}
        <div class="card border-success mr-2 mb-2">
            <div class="card-body">
                <h4 class="card-title">{{ stinky }}</h4>
                {% if stinky.is_for_trade %}
                <a class="btn btn-danger btn-sm" href="{% url "game1:dont-trade-stinky" stinky.id %}">Don't trade</a>
                {% else %}
                <a class="btn btn-info btn-sm" href="{% url "game1:trade-stinky" stinky.id %}">Trade</a>
                {% endif %}
                <a class="btn btn-secondary btn-sm" href="{% url "game1:sell-back-stinky" stinky.id %}">Sell</a>
            </div>
        </div>
    {% endfor %}
    </div>
    <div class="col-4">
        {% if player.coins >= 2 %}
        <div class="card border-warning mb-4">
            <div class="card-body">
                <h4>Buy a stinky</h4>
                <a class="btn btn-warning" href="{% url "game1:buy-new-stinky" %}">2 coins</a>
            </div>
        </div>
        {% endif %}

        <h2>Your friends:</h2>
        {% for friend in friends %}
            <a href="{% url "game1:view-player" friend %}" class="btn btn-outline-success">{{ friend }}</a>
        {% endfor %}
        <div class="text-center">
            <a class="btn btn-primary" href="{% url "friendship_view_users" %}">Add a friend</a>
        </div>
    </div>
</div>
{% endblock %}

stinkies/templates/game1/layout.html
{% extends "portal/base.html" %}
{% load static %}

{% block body_css %}
    background: url('{% static "img/g1bg.png" %}') no-repeat center center fixed;
{% endblock %}

{% block navbar %}
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url "game1:homepage" %}">{{ request.user }}'s Stinkies</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">Coins: {{ player.coins|default:0 }}</a>
        </li>
    </ul>
{% endblock %}

stinkies/templates/game1/player_details.html
{% extends "game1/layout.html" %}

{% block content %}
    <h1>{{ player2 }}'s Stinkies</h1>
    <h2>Their inventory:</h2>
    <div class="row mb-3">
        <div class="col-8">
            {% for stinky in player2.user.inventory.all %}
                <div class="card {% if stinky.is_for_trade %}border-danger{% else %}border-success{% endif %} mr-2 mb-2">
                    <div class="card-body">
                        <h4 class="card-title">{{ stinky }}</h4>
                        {% comment %}
                        <a class="btn btn-info btn-sm" href="#">Trade</a>
                        <a class="btn btn-secondary btn-sm" href="{% url "game1:sell-back-stinky" stinky.id %}">Sell</a>
                        {% endcomment %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-4">

        </div>
    </div>
{% endblock %}

stinkies/templates/portal/base.html
{% load static %}{% load bootstrap4 %}<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Stinky Games</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <style type="text/css">
            body {
            {% block body_css %}
                background: url('{% static "img/stbg.jpg" %}') no-repeat center center fixed;
            {% endblock %}
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover;
                height: 100%;
            }
            main.container {
                background-color: #E5FFE1;
            }
            .min-100 {
                min-height: 85%;
            }
            footer>div.container {
                background-color: #E5FFE1;
            }
        </style>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url "homepage" %}">Stinky Games</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% block navbar %}
        {% endblock %}
            </div>
        </nav>

        <main role="main" class="container min-100 pt-3">
            {% bootstrap_messages %}
            {% block content %}{% endblock %}
        </main>

        <footer class="footer mt-auto py-3">
            <div class="container">
                <span class="text-muted text-center">Copyright &copy; 2020 A115 Ltd.</span>
            </div>
        </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script type="application/javascript">
        {% block extra_js %}
        {% endblock %}
    </script>
    </body>
</html>

stinkies/templates/portal/homepage.html
{% extends "portal/base.html" %}
{% load static %}

{% block navbar %}
<ul class="navbar-nav mr-auto">
    <li class="nav-item">
        <a class="nav-link" href="{% url "game1:homepage" %}">Play</a>
    </li>
    {% if request.user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "logout" %}?next=/">Sign out</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "django_registration_register" %}">New player</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "login" %}">Sign in</a>
    </li>
    {% endif %}
</ul>
{% endblock %}

{% block content %}
<div class="text-center mb-4">
    <h1>Welcome to stinky games{% if request.user.is_authenticated %}, {{ request.user }}{% endif %}!</h1>
    <img class="image" width=320 src="{% static "img/art/stinky-cheese.png" %}" title="Stinky games" alt="Stinky games" />
    <h3>Soon, you too shall stink :) </h3>
</div>

<div class="text-center">
    <a href="{% url "game1:homepage" %}" class="btn btn-lg btn-info">Play Stinkies</a>
</div>

{% if frqs %}
    <form class="d-none" id="frq_form" method="POST" action="">{% csrf_token %}
        <input type="submit" value="action friend request" />
    </form>
{% endif %}
{% endblock %}

{% block extra_js %}
function accept_frq(username) {
    var frm = $('#frq_form');
    base_url = "{% url "friendship_accept" 0 %}";
    post_url = base_url.replace('0', username);
    frm.attr('action', post_url);
    frm.submit();
};

function reject_frq(username) {
    var frm = $('#frq_form');
    base_url = "{% url "friendship_reject" 0 %}";
    post_url = base_url.replace('0', username);
    frm.attr('action', post_url);
    frm.submit();
};
{% endblock %}